package lucenenewsgroups;

/**
 * Static class used to hold information about the application, such as the
 * name and the version
 * @author Luciano Mammino <lmammino[at]oryzone[dot]com>
 * @version 1.0
 */
public class AppInfo
{

    private AppInfo()
    {
        //just to avoid to instantiate objects from this class
    }

    /**
     * The name of the application
     */
    public static String name = "LuceneNewsGroups";

    /**
     * The version of the application
     */
    public static String version = "1.0";


    /**
     * The name of the index file generated by the command generateIndex
     */
    public static String indexFile = ".lucene_newsgroups_index";

}